//
//  Contants.swift
//  FarmEducation
//
//  Created by Sevinj Shahmaliyeva on 12.08.25.
//

import Foundation

struct Constants {
    static let smallCould = "smallCould"
    static let falseImage = "falseImage"
    static let rightImage = "rightImage"
    static let exit = "Exit"
    static let turnUp = "arrowshape.turn.up.backward.fill"
    static let whosePart = "whosePart"
    static let newGame = "New game"
    static let play = "Play"
    static let lastScore = "Last Score:"
    static let bestScore = "Best Score:"
    static let from = "from"
    static let correct = "correct"
    static let error = "error"
    
    //places
    static let farmBackground = "farmBackground"
    static let questionBackgroud = "questionBackgroud"
    static let forest = "forest"
    
    
    //animals
    static let cat = "cat"
    static let cow = "cow"
    static let dog = "dog"
    static let pig = "pig"
    static let sheep = "sheep"
    static let rabbit = "rabbit"
    static let horse = "horse"
    static let donkey = "donkey"
    static let chicken = "chicken"
    static let duck = "duck"
    static let goose = "goose"
    static let goat = "goat"
    static let fox = "fox"
    static let lion = "lion"
    static let wolf = "wolf"
    static let bear = "bear"
    static let deer = "deer"
    static let antelope = "antelope"
    static let panda = "panda"
    static let giraffe = "giraffe"
    static let monkey = "monkey"
    static let zebra = "zebra"
    static let tiger = "tiger"
    static let leopard = "leopard"
    static let elephant = "elephant"
    static let hippopotamus = "hippopotamus"
    static let camel = "camel"
    static let rhinoceros = "rhinoceros"
    static let hedgehog = "hedgehog"
    static let turtle = "turtle"
    static let beaver = "beaver"
    static let squirrel = "squirrel"
    static let gazelle = "gazelle"
    static let badger = "badger"
    static let jackal = "jackal"
    static let llama = "llama"
    static let mouse = "mouse"
    static let kangaroo = "kangaroo"
    static let meerkat = "meerkat"
    static let crocodile = "crocodile"
    static let fish = "fish"
    static let snake = "snake"
    static let blackAntelope = "blackAntelope"
    
    // meal
    static let apple = "apple"
    static let banana = "banana"
    static let bamboo = "bamboo"
    static let broccoli = "broccoli"
    static let cabbage = "cabbage"
    static let carrot = "carrot"
    static let cherry = "cherry"
    static let corn = "corn"
    static let cucumber = "cucumber"
    static let egg = "egg"
    static let grass = "grass"
    static let grapes = "grapes"
    static let hay = "hay"
    static let meat = "meat"
    static let mushroom = "mushroom"
    static let nuts = "nuts"
    static let pear = "pear"
    static let pineapple = "pineapple"
    static let potato = "potato"
    static let pumpkin = "pumpkin"
    static let rice = "rice"
    static let strawberry = "strawberry"
    static let watermelon = "watermelon"
    static let cheese = "cheese"
    static let onion = "onion"
    static let garlic = "garlic"
    
    //gametype
    static let whatAnimalsEat = "What does this animal eat?"
    static let whereAnimalsLive = "Which animal lives here?"
    static let whichAnimalsShadow = "Whose shadow is this?"
    static let whosePartIsThis = "Whose body part is this?"
    static let whoIsMyPair = "Match the Animals"
    
    //colors
    static let  forestColor = "forestColor"
    static let homeColor = "homeColor"
    static let farmColor = "farmColor"
    static let desertColor = "desertColor"
    static let oceanColor = "oceanColor"
}
